import type { Locale } from "@/lib/constants";

export const imageToolIds = [
  "image-resizer",
  "image-compressor",
  "image-cropper",
  "image-to-base64",
  "base64-to-image",
  "image-format-converter",
  "image-metadata-reader"
] as const;

export type ImageToolId = (typeof imageToolIds)[number];

export const imageUiLabels: Record<Locale, Record<string, string>> = {
  en: {
    file: "Image file",
    width: "Width",
    height: "Height",
    quality: "Quality",
    format: "Format",
    keepAspectRatio: "Keep aspect ratio",
    cropX: "Crop X",
    cropY: "Crop Y",
    cropWidth: "Crop width",
    cropHeight: "Crop height",
    originalSize: "Original size",
    outputSize: "Output size",
    savedSize: "Saved size",
    preview: "Preview",
    result: "Result",
    download: "Download",
    upload: "Upload image",
    base64: "Base64 value",
    mimeType: "MIME type",
    resizedImage: "Resized image",
    compressedImage: "Compressed image",
    croppedImage: "Cropped image",
    convertedImage: "Converted image",
    decodedImage: "Decoded image",
    imagePreview: "Image preview",
    camera: "Camera",
    lens: "Lens",
    dateTaken: "Date taken",
    resolution: "Resolution",
    fileSize: "File size",
    iso: "ISO",
    exposure: "Exposure",
    aperture: "Aperture",
    focalLength: "Focal length",
    flash: "Flash",
    orientation: "Orientation",
    latitude: "Latitude",
    longitude: "Longitude",
    openMap: "Open map",
    rawMetadata: "Raw metadata",
    noMetadataFound: "No photo metadata was found in this file.",
    gpsLocation: "GPS location",
    metadataSummary: "Metadata summary",
    copy: "Copy",
    copied: "Copied",
    clear: "Clear"
  },
  pl: {
    file: "Plik obrazu",
    width: "Szerokosc",
    height: "Wysokosc",
    quality: "Jakosc",
    format: "Format",
    keepAspectRatio: "Zachowaj proporcje",
    cropX: "Przyciecie X",
    cropY: "Przyciecie Y",
    cropWidth: "Szerokosc kadru",
    cropHeight: "Wysokosc kadru",
    originalSize: "Rozmiar oryginalu",
    outputSize: "Rozmiar wyniku",
    savedSize: "Zaoszczedzone miejsce",
    preview: "Podglad",
    result: "Wynik",
    download: "Pobierz",
    upload: "Wgraj obraz",
    base64: "Wartosc Base64",
    mimeType: "Typ MIME",
    resizedImage: "Zmniejszony obraz",
    compressedImage: "Skompresowany obraz",
    croppedImage: "Przycięty obraz",
    convertedImage: "Skonwertowany obraz",
    decodedImage: "Odtworzony obraz",
    imagePreview: "Podglad obrazu",
    camera: "Aparat",
    lens: "Obiektyw",
    dateTaken: "Data wykonania",
    resolution: "Rozdzielczosc",
    fileSize: "Rozmiar pliku",
    iso: "ISO",
    exposure: "Ekspozycja",
    aperture: "Przyslona",
    focalLength: "Ogniskowa",
    flash: "Lampa blyskowa",
    orientation: "Orientacja",
    latitude: "Szerokosc geo",
    longitude: "Dlugosc geo",
    openMap: "Otworz mape",
    rawMetadata: "Surowe metadane",
    noMetadataFound: "W tym pliku nie znaleziono metadanych zdjecia.",
    gpsLocation: "Lokalizacja GPS",
    metadataSummary: "Podsumowanie metadanych",
    copy: "Kopiuj",
    copied: "Skopiowano",
    clear: "Wyczysc"
  },
  es: {
    file: "Archivo de imagen",
    width: "Ancho",
    height: "Alto",
    quality: "Calidad",
    format: "Formato",
    keepAspectRatio: "Mantener proporcion",
    cropX: "Recorte X",
    cropY: "Recorte Y",
    cropWidth: "Ancho del recorte",
    cropHeight: "Alto del recorte",
    originalSize: "Tamano original",
    outputSize: "Tamano final",
    savedSize: "Tamano ahorrado",
    preview: "Vista previa",
    result: "Resultado",
    download: "Descargar",
    upload: "Subir imagen",
    base64: "Valor Base64",
    mimeType: "Tipo MIME",
    resizedImage: "Imagen redimensionada",
    compressedImage: "Imagen comprimida",
    croppedImage: "Imagen recortada",
    convertedImage: "Imagen convertida",
    decodedImage: "Imagen decodificada",
    imagePreview: "Vista de imagen",
    camera: "Camara",
    lens: "Lente",
    dateTaken: "Fecha de captura",
    resolution: "Resolucion",
    fileSize: "Tamano del archivo",
    iso: "ISO",
    exposure: "Exposicion",
    aperture: "Apertura",
    focalLength: "Distancia focal",
    flash: "Flash",
    orientation: "Orientacion",
    latitude: "Latitud",
    longitude: "Longitud",
    openMap: "Abrir mapa",
    rawMetadata: "Metadatos sin procesar",
    noMetadataFound: "No se encontraron metadatos de la foto en este archivo.",
    gpsLocation: "Ubicacion GPS",
    metadataSummary: "Resumen de metadatos",
    copy: "Copiar",
    copied: "Copiado",
    clear: "Limpiar"
  },
  de: {
    file: "Bilddatei",
    width: "Breite",
    height: "Hoehe",
    quality: "Qualitaet",
    format: "Format",
    keepAspectRatio: "Seitenverhaeltnis behalten",
    cropX: "Beschnitt X",
    cropY: "Beschnitt Y",
    cropWidth: "Beschnittbreite",
    cropHeight: "Beschnitthoehe",
    originalSize: "Originalgroesse",
    outputSize: "Ausgabegroesse",
    savedSize: "Ersparnis",
    preview: "Vorschau",
    result: "Ergebnis",
    download: "Herunterladen",
    upload: "Bild hochladen",
    base64: "Base64 Wert",
    mimeType: "MIME Typ",
    resizedImage: "Skaliertes Bild",
    compressedImage: "Komprimiertes Bild",
    croppedImage: "Zugeschnittenes Bild",
    convertedImage: "Konvertiertes Bild",
    decodedImage: "Dekodiertes Bild",
    imagePreview: "Bildvorschau",
    camera: "Kamera",
    lens: "Objektiv",
    dateTaken: "Aufnahmedatum",
    resolution: "Aufloesung",
    fileSize: "Dateigroesse",
    iso: "ISO",
    exposure: "Belichtung",
    aperture: "Blende",
    focalLength: "Brennweite",
    flash: "Blitz",
    orientation: "Ausrichtung",
    latitude: "Breitengrad",
    longitude: "Laengengrad",
    openMap: "Karte oeffnen",
    rawMetadata: "Rohe Metadaten",
    noMetadataFound: "In dieser Datei wurden keine Fotometadaten gefunden.",
    gpsLocation: "GPS Standort",
    metadataSummary: "Metadaten-Uebersicht",
    copy: "Kopieren",
    copied: "Kopiert",
    clear: "Leeren"
  },
  fr: {
    file: "Fichier image",
    width: "Largeur",
    height: "Hauteur",
    quality: "Qualite",
    format: "Format",
    keepAspectRatio: "Garder les proportions",
    cropX: "Recadrage X",
    cropY: "Recadrage Y",
    cropWidth: "Largeur du recadrage",
    cropHeight: "Hauteur du recadrage",
    originalSize: "Taille d'origine",
    outputSize: "Taille finale",
    savedSize: "Taille economisee",
    preview: "Apercu",
    result: "Resultat",
    download: "Telecharger",
    upload: "Envoyer une image",
    base64: "Valeur Base64",
    mimeType: "Type MIME",
    resizedImage: "Image redimensionnee",
    compressedImage: "Image compressee",
    croppedImage: "Image recadree",
    convertedImage: "Image convertie",
    decodedImage: "Image decodee",
    imagePreview: "Apercu image",
    camera: "Appareil",
    lens: "Objectif",
    dateTaken: "Date de prise",
    resolution: "Resolution",
    fileSize: "Taille du fichier",
    iso: "ISO",
    exposure: "Exposition",
    aperture: "Ouverture",
    focalLength: "Focale",
    flash: "Flash",
    orientation: "Orientation",
    latitude: "Latitude",
    longitude: "Longitude",
    openMap: "Ouvrir la carte",
    rawMetadata: "Metadonnees brutes",
    noMetadataFound: "Aucune metadonnee photo n'a ete trouvee dans ce fichier.",
    gpsLocation: "Localisation GPS",
    metadataSummary: "Resume des metadonnees",
    copy: "Copier",
    copied: "Copie",
    clear: "Effacer"
  }
};
