import type { Locale } from "@/lib/constants";

export const generatorToolIds = [
  "qr-code-generator",
  "gradient-generator",
  "box-shadow-generator",
  "favicon-generator",
  "placeholder-image-generator",
  "meta-tag-generator"
] as const;

export type GeneratorToolId = (typeof generatorToolIds)[number];

export const generatorUiLabels: Record<Locale, Record<string, string>> = {
  en: {
    text: "Text",
    file: "Image file",
    width: "Width",
    height: "Height",
    size: "Size",
    format: "Format",
    quality: "Quality",
    colorOne: "Color one",
    colorTwo: "Color two",
    background: "Background",
    foreground: "Foreground",
    angle: "Angle",
    margin: "Margin",
    level: "Error correction",
    gradientType: "Gradient type",
    linear: "Linear",
    radial: "Radial",
    blur: "Blur",
    spread: "Spread",
    offsetX: "Offset X",
    offsetY: "Offset Y",
    opacity: "Opacity",
    inset: "Inset shadow",
    cssCode: "CSS code",
    snippet: "Meta tags",
    preview: "Preview",
    download: "Download",
    downloadSvg: "Download SVG",
    downloadPng: "Download PNG",
    downloadAll: "Download all",
    upload: "Upload image",
    copied: "Copied",
    copy: "Copy",
    title: "Title",
    description: "Description",
    canonicalUrl: "Canonical URL",
    siteName: "Site name",
    ogImage: "OG image URL",
    clear: "Clear",
    generatedQr: "Generated QR code",
    placeholderImage: "Placeholder image",
    faviconSet: "Favicon set"
  },
  pl: {
    text: "Tekst",
    file: "Plik obrazu",
    width: "Szerokosc",
    height: "Wysokosc",
    size: "Rozmiar",
    format: "Format",
    quality: "Jakosc",
    colorOne: "Kolor pierwszy",
    colorTwo: "Kolor drugi",
    background: "Tlo",
    foreground: "Kolor kodu",
    angle: "Kat",
    margin: "Margines",
    level: "Poziom korekcji",
    gradientType: "Typ gradientu",
    linear: "Liniowy",
    radial: "Radialny",
    blur: "Rozmycie",
    spread: "Rozszerzenie",
    offsetX: "Przesuniecie X",
    offsetY: "Przesuniecie Y",
    opacity: "Przezroczystosc",
    inset: "Cien wewnetrzny",
    cssCode: "Kod CSS",
    snippet: "Znaczniki meta",
    preview: "Podglad",
    download: "Pobierz",
    downloadSvg: "Pobierz SVG",
    downloadPng: "Pobierz PNG",
    downloadAll: "Pobierz wszystko",
    upload: "Wgraj obraz",
    copied: "Skopiowano",
    copy: "Kopiuj",
    title: "Tytul",
    description: "Opis",
    canonicalUrl: "URL kanoniczny",
    siteName: "Nazwa strony",
    ogImage: "URL obrazu OG",
    clear: "Wyczysc",
    generatedQr: "Wygenerowany kod QR",
    placeholderImage: "Obraz placeholder",
    faviconSet: "Zestaw favicon"
  },
  es: {
    text: "Texto",
    file: "Archivo de imagen",
    width: "Ancho",
    height: "Alto",
    size: "Tamano",
    format: "Formato",
    quality: "Calidad",
    colorOne: "Color uno",
    colorTwo: "Color dos",
    background: "Fondo",
    foreground: "Color del codigo",
    angle: "Angulo",
    margin: "Margen",
    level: "Correccion",
    gradientType: "Tipo de gradiente",
    linear: "Lineal",
    radial: "Radial",
    blur: "Desenfoque",
    spread: "Expansion",
    offsetX: "Desplazamiento X",
    offsetY: "Desplazamiento Y",
    opacity: "Opacidad",
    inset: "Sombra interna",
    cssCode: "Codigo CSS",
    snippet: "Etiquetas meta",
    preview: "Vista previa",
    download: "Descargar",
    downloadSvg: "Descargar SVG",
    downloadPng: "Descargar PNG",
    downloadAll: "Descargar todo",
    upload: "Subir imagen",
    copied: "Copiado",
    copy: "Copiar",
    title: "Titulo",
    description: "Descripcion",
    canonicalUrl: "URL canonica",
    siteName: "Nombre del sitio",
    ogImage: "URL de imagen OG",
    clear: "Limpiar",
    generatedQr: "Codigo QR generado",
    placeholderImage: "Imagen placeholder",
    faviconSet: "Set de favicon"
  },
  de: {
    text: "Text",
    file: "Bilddatei",
    width: "Breite",
    height: "Hoehe",
    size: "Groesse",
    format: "Format",
    quality: "Qualitaet",
    colorOne: "Farbe eins",
    colorTwo: "Farbe zwei",
    background: "Hintergrund",
    foreground: "Codefarbe",
    angle: "Winkel",
    margin: "Rand",
    level: "Fehlerkorrektur",
    gradientType: "Gradienttyp",
    linear: "Linear",
    radial: "Radial",
    blur: "Weichzeichnung",
    spread: "Ausbreitung",
    offsetX: "Versatz X",
    offsetY: "Versatz Y",
    opacity: "Deckkraft",
    inset: "Innenschatten",
    cssCode: "CSS Code",
    snippet: "Meta Tags",
    preview: "Vorschau",
    download: "Herunterladen",
    downloadSvg: "SVG herunterladen",
    downloadPng: "PNG herunterladen",
    downloadAll: "Alles herunterladen",
    upload: "Bild hochladen",
    copied: "Kopiert",
    copy: "Kopieren",
    title: "Titel",
    description: "Beschreibung",
    canonicalUrl: "Kanonische URL",
    siteName: "Seitenname",
    ogImage: "OG Bild URL",
    clear: "Leeren",
    generatedQr: "Generierter QR Code",
    placeholderImage: "Placeholder Bild",
    faviconSet: "Favicon Set"
  },
  fr: {
    text: "Texte",
    file: "Fichier image",
    width: "Largeur",
    height: "Hauteur",
    size: "Taille",
    format: "Format",
    quality: "Qualite",
    colorOne: "Couleur une",
    colorTwo: "Couleur deux",
    background: "Fond",
    foreground: "Couleur du code",
    angle: "Angle",
    margin: "Marge",
    level: "Correction",
    gradientType: "Type de gradient",
    linear: "Lineaire",
    radial: "Radial",
    blur: "Flou",
    spread: "Etendue",
    offsetX: "Decalage X",
    offsetY: "Decalage Y",
    opacity: "Opacite",
    inset: "Ombre interne",
    cssCode: "Code CSS",
    snippet: "Balises meta",
    preview: "Apercu",
    download: "Telecharger",
    downloadSvg: "Telecharger SVG",
    downloadPng: "Telecharger PNG",
    downloadAll: "Tout telecharger",
    upload: "Envoyer une image",
    copied: "Copie",
    copy: "Copier",
    title: "Titre",
    description: "Description",
    canonicalUrl: "URL canonique",
    siteName: "Nom du site",
    ogImage: "URL image OG",
    clear: "Effacer",
    generatedQr: "Code QR genere",
    placeholderImage: "Image placeholder",
    faviconSet: "Pack favicon"
  }
};
